-- Create attendance_records table
CREATE TABLE IF NOT EXISTS attendance_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT REFERENCES students(id) ON DELETE CASCADE,
  date DATE NOT NULL DEFAULT CURRENT_DATE,
  status TEXT NOT NULL CHECK (status IN ('present', 'late', 'absent', 'excused')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
  
  -- Prevent duplicate records for the same student on the same day
  UNIQUE(student_id, date)
);

-- RLS Policies (Enable Row Level Security)
ALTER TABLE attendance_records ENABLE ROW LEVEL SECURITY;

-- Allow read access to authenticated users (teachers/admins)
CREATE POLICY "Allow read access to authenticated users" ON attendance_records
  FOR SELECT TO authenticated USING (true);

-- Allow insert/update access to authenticated users
CREATE POLICY "Allow insert/update access to authenticated users" ON attendance_records
  FOR ALL TO authenticated USING (true);
