-- Create neighborhoods table
CREATE TABLE IF NOT EXISTS neighborhoods (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  state BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS
ALTER TABLE neighborhoods ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Neighborhoods are viewable by everyone." ON neighborhoods FOR SELECT USING (true);
CREATE POLICY "Admins and teachers can manage neighborhoods." ON neighborhoods FOR ALL TO authenticated USING (true);

-- Comment for documentation
COMMENT ON TABLE neighborhoods IS 'Maestro de barrios o ubicaciones de la institución educativa.';
