-- Create a table for public profiles
create table profiles (
  id uuid references auth.users on delete cascade not null primary key,
  updated_at timestamp with time zone,
  full_name text,
  avatar_url text,
  role text check (role in ('admin', 'teacher', 'parent', 'student')) default 'student',
  
  constraint username_length check (char_length(full_name) >= 3)
);

-- Set up Row Level Security (RLS)
-- See https://supabase.com/docs/guides/auth/row-level-security for more details.
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Users can insert their own profile." on profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on profiles
  for update using (auth.uid() = id);

-- Grades (Grados/Cursos)
create table grades (
  id bigint generated by default as identity primary key,
  name text not null, -- e.g. "10A"
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table grades enable row level security;
create policy "Grades are viewable by everyone." on grades for select using (true);
create policy "Admins can insert grades." on grades for insert with check (exists (select 1 from profiles where id = auth.uid() and role = 'admin'));

-- Students
create table students (
  id bigint generated by default as identity primary key,
  first_name text not null,
  last_name text not null,
  grade_id bigint references grades(id) on delete set null,
  parent_id uuid references profiles(id) on delete set null, -- Link to a parent user
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table students enable row level security;
create policy "Authenticated users can view students." on students for select using (auth.role() = 'authenticated');
create policy "Admins and Teachers can insert students." on students for insert with check (
  exists (select 1 from profiles where id = auth.uid() and role in ('admin', 'teacher'))
);

-- Attendance (Asistencia)
create table attendance (
  id bigint generated by default as identity primary key,
  student_id bigint references students(id) on delete cascade not null,
  date date not null default current_date,
  status text check (status in ('present', 'absent', 'late', 'excused')) not null,
  marked_by uuid references profiles(id) on delete set null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  unique(student_id, date) -- One record per student per day
);

alter table attendance enable row level security;
-- Everyone can view attendance (filtering will be done in app)
create policy "View attendance" on attendance for select using (auth.role() = 'authenticated');
-- Only teachers and admins can mark attendance
create policy "Teachers create attendance" on attendance for insert with check (
  exists (select 1 from profiles where id = auth.uid() and role in ('admin', 'teacher'))
);
