-- Subjects (Asignaturas)
create table subjects (
  id bigint generated by default as identity primary key,
  name text not null, -- e.g. "Matemáticas", "Ciencias"
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table subjects enable row level security;
create policy "Read subjects" on subjects for select using (true);
create policy "Admins manage subjects" on subjects for all using (
  exists (select 1 from profiles where id = auth.uid() and role = 'admin')
);

-- Assignments (Asignaciones: Profesor -> Grado -> Asignatura)
create table assignments (
  id bigint generated by default as identity primary key,
  teacher_id uuid references profiles(id) on delete cascade not null,
  grade_id bigint references grades(id) on delete cascade not null,
  subject_id bigint references subjects(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  unique(teacher_id, grade_id, subject_id)
);

alter table assignments enable row level security;
create policy "Read assignments" on assignments for select using (true);
create policy "Admins manage assignments" on assignments for all using (
  exists (select 1 from profiles where id = auth.uid() and role = 'admin')
);
